"""removed file_path property from image

Revision ID: 78217b75a42d
Revises: 06e2677a2e0e
Create Date: 2025-08-30 14:59:17.095738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # Add SQLModel import


# revision identifiers, used by Alembic.
revision: str = '78217b75a42d'
down_revision: Union[str, None] = '06e2677a2e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
