"""added images field

Revision ID: 06e2677a2e0e
Revises: 9b7c414dac40
Create Date: 2025-08-29 14:30:14.944876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # Add SQLModel import


# revision identifiers, used by Alembic.
revision: str = '06e2677a2e0e'
down_revision: Union[str, None] = '9b7c414dac40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('seller_profile_id', sa.Uuid(), nullable=True),
    sa.Column('user_profile_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['seller_profile_id'], ['seller_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_category_id'), 'images', ['category_id'], unique=False)
    op.create_index(op.f('ix_images_file_name'), 'images', ['file_name'], unique=False)
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_index(op.f('ix_images_product_id'), 'images', ['product_id'], unique=False)
    op.create_index(op.f('ix_images_seller_profile_id'), 'images', ['seller_profile_id'], unique=False)
    op.create_index(op.f('ix_images_user_profile_id'), 'images', ['user_profile_id'], unique=False)
    op.drop_column('categories', 'main_image_url')
    op.drop_column('products', 'main_image_url')
    op.drop_column('seller_profiles', 'main_image_url')
    op.drop_column('user_profiles', 'main_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('main_image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('seller_profiles', sa.Column('main_image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('main_image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('main_image_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_images_user_profile_id'), table_name='images')
    op.drop_index(op.f('ix_images_seller_profile_id'), table_name='images')
    op.drop_index(op.f('ix_images_product_id'), table_name='images')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_index(op.f('ix_images_file_name'), table_name='images')
    op.drop_index(op.f('ix_images_category_id'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
